export * from './add-professor-controller'
export * from './load-professor-controller'
export * from './update-professor-controller'
export * from './add-disciplina-controller'
export * from './add-turma-controller'
export * from './login-controller'
export * from './signup-controller'
