export * from './professor-postgres-repository'
export * from './disciplina-postgres-repository'
export * from './turma-postgres-repository'
export * from './account-postgres-repository'
export * from './log-error-postgres-repository'
